Moving users to .data/users

diff --git a/bin/cliferay b/bin/cliferay
--- a/bin/cliferay
+++ b/bin/cliferay
@@ -133,6 +133,27 @@ cliferay() {
   }
 
   # :command.usage
+  cliferay_data_folder_usage() {
+    printf "cliferay data-folder - Print the data folder\n\n"
+
+    printf "%s\n" "$(bold "Usage:")"
+    printf "  cliferay data-folder\n"
+    printf "  cliferay data-folder --help | -h\n"
+    echo
+
+    # :command.long_usage
+    if [[ -n "$long_usage" ]]; then
+      printf "%s\n" "$(bold "Options:")"
+
+      # :command.usage_fixed_flags
+      printf "  %s\n" "--help, -h"
+      printf "    Show this help\n"
+      echo
+
+    fi
+  }
+
+  # :command.usage
   cliferay_init_usage() {
     printf "cliferay init - Initialize cliferay\n\n"
 
@@ -1787,6 +1808,13 @@ cliferay() {
   }
 
   # :command.function
+  cliferay_data_folder_command() {
+
+    # src/commands/data-folder.sh
+    echo $(dirname "$(readlink -f "$0")")/../.data
+  }
+
+  # :command.function
   cliferay_init_command() {
 
     # src/commands/init.sh
@@ -2312,14 +2340,14 @@ EOF
   cliferay_stats_users_jira_command() {
 
     # src/commands/stats/users/jira.sh
-    grep "^${args["user"]}" $(dirname "$(readlink -f "$0")")/users | awk '{print $2}'
+    grep "^${args["user"]}" $(cliferay data-folder)/users | awk '{print $2}'
   }
 
   # :command.function
   cliferay_stats_users_emails_command() {
 
     # src/commands/stats/users/emails.sh
-    grep "^${args["user"]}" $(dirname "$(readlink -f "$0")")/users | awk '{for (i=3; i<=NF; i++) print $i}'
+    grep "^${args["user"]}" $(cliferay data-folder)/users | awk '{for (i=3; i<=NF; i++) print $i}'
   }
 
   # :command.function
@@ -2471,6 +2499,13 @@ EOF
         action="completions"
         shift
         cliferay_completions_parse_requirements "$@"
+        shift $#
+        ;;
+
+      data-folder)
+        action="data-folder"
+        shift
+        cliferay_data_folder_parse_requirements "$@"
         shift $#
         ;;
 
@@ -2800,6 +2835,51 @@ EOF
 
     # :command.command_filter
     action="completions"
+
+    # :command.parse_requirements_while
+    while [[ $# -gt 0 ]]; do
+      key="$1"
+      case "$key" in
+
+        -?*)
+          printf "invalid option: %s\n" "$key" >&2
+          exit 1
+          ;;
+
+        *)
+          # :command.parse_requirements_case
+          # :command.parse_requirements_case_simple
+          printf "invalid argument: %s\n" "$key" >&2
+          exit 1
+
+          ;;
+
+      esac
+    done
+
+  }
+
+  # :command.parse_requirements
+  cliferay_data_folder_parse_requirements() {
+    # :command.fixed_flags_filter
+    while [[ $# -gt 0 ]]; do
+      key="$1"
+      case "$key" in
+        --help | -h)
+          long_usage=yes
+          cliferay_data_folder_usage
+          exit
+          ;;
+
+        *)
+          break
+          ;;
+
+      esac
+    done
+
+    # :command.command_filter
+    action="data-folder"
 
     # :command.parse_requirements_while
     while [[ $# -gt 0 ]]; do
@@ -5306,6 +5386,7 @@ EOF
     case "$action" in
       "aliases") cliferay_aliases_command ;;
       "completions") cliferay_completions_command ;;
+      "data-folder") cliferay_data_folder_command ;;
       "init") cliferay_init_command ;;
       "update") cliferay_update_command ;;
       "ant") cliferay_ant_command ;;
