Adding baseline command

diff --git a/cliferay b/cliferay
--- a/cliferay
+++ b/cliferay
@@ -51,6 +51,7 @@ cliferay_usage() {
   printf "  %s   Deploy changed modules\n" "super-deploy   "
   printf "  %s   Run SF globally\n" "format-source  "
   printf "  %s   Deploy the current folder\n" "deploy         "
+  printf "  %s   Run baseline in the current folder\n" "baseline       "
   printf "  %s   Run a Poshi test\n" "poshi          "
   echo
   printf "%s\n" "Server Commands:"
@@ -613,6 +614,27 @@ cliferay_deploy_usage() {
   printf "%s\n" "Usage:"
   printf "  cliferay deploy\n"
   printf "  cliferay deploy --help | -h\n"
+  echo
+
+  # :command.long_usage
+  if [[ -n $long_usage ]]; then
+    printf "%s\n" "Options:"
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "--help, -h"
+    printf "    Show this help\n"
+    echo
+
+  fi
+}
+
+# :command.usage
+cliferay_baseline_usage() {
+  printf "cliferay baseline - Run baseline in the current folder\n\n"
+
+  printf "%s\n" "Usage:"
+  printf "  cliferay baseline\n"
+  printf "  cliferay baseline --help | -h\n"
   echo
 
   # :command.long_usage
@@ -1291,16 +1313,16 @@ send_completions() {
   echo $'      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_cliferay_completions_filter "--help -h")" -- "$cur")'
   echo $'      ;;'
   echo $''
+  echo $'    \'super-deploy\'*)'
+  echo $'      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_cliferay_completions_filter "--branch --help -b -h")" -- "$cur")'
+  echo $'      ;;'
+  echo $''
   echo $'    \'curl new-api\'*)'
   echo $'      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_cliferay_completions_filter "--help -h")" -- "$cur")'
   echo $'      ;;'
   echo $''
   echo $'    \'stats review\'*)'
   echo $'      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_cliferay_completions_filter "--help -h")" -- "$cur")'
-  echo $'      ;;'
-  echo $''
-  echo $'    \'super-deploy\'*)'
-  echo $'      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_cliferay_completions_filter "--branch --help -b -h")" -- "$cur")'
   echo $'      ;;'
   echo $''
   echo $'    \'stats years\'*)'
@@ -1311,6 +1333,10 @@ send_completions() {
   echo $'      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_cliferay_completions_filter "--branch --help -b -h")" -- "$cur")'
   echo $'      ;;'
   echo $''
+  echo $'    \'baseline\'*)'
+  echo $'      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_cliferay_completions_filter "--help -h")" -- "$cur")'
+  echo $'      ;;'
+  echo $''
   echo $'    \'backport\'*)'
   echo $'      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_cliferay_completions_filter "--branch --help -b -h")" -- "$cur")'
   echo $'      ;;'
@@ -1319,11 +1345,11 @@ send_completions() {
   echo $'      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_cliferay_completions_filter "--force --help --no-nuke -f -h")" -- "$cur")'
   echo $'      ;;'
   echo $''
-  echo $'    \'db-name\'*)'
+  echo $'    \'tickets\'*)'
   echo $'      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_cliferay_completions_filter "--help -h")" -- "$cur")'
   echo $'      ;;'
   echo $''
-  echo $'    \'tickets\'*)'
+  echo $'    \'db-name\'*)'
   echo $'      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_cliferay_completions_filter "--help -h")" -- "$cur")'
   echo $'      ;;'
   echo $''
@@ -1343,6 +1369,10 @@ send_completions() {
   echo $'      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_cliferay_completions_filter "--help -h")" -- "$cur")'
   echo $'      ;;'
   echo $''
+  echo $'    \'poshi\'*)'
+  echo $'      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_cliferay_completions_filter "--help -h")" -- "$cur")'
+  echo $'      ;;'
+  echo $''
   echo $'    \'stats\'*)'
   echo $'      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_cliferay_completions_filter "--help -h commits ranking review tickets years")" -- "$cur")'
   echo $'      ;;'
@@ -1351,15 +1381,7 @@ send_completions() {
   echo $'      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_cliferay_completions_filter "--help -h")" -- "$cur")'
   echo $'      ;;'
   echo $''
-  echo $'    \'poshi\'*)'
-  echo $'      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_cliferay_completions_filter "--help -h")" -- "$cur")'
-  echo $'      ;;'
-  echo $''
   echo $'    \'jira\'*)'
-  echo $'      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_cliferay_completions_filter "--help -h")" -- "$cur")'
-  echo $'      ;;'
-  echo $''
-  echo $'    \'kill\'*)'
   echo $'      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_cliferay_completions_filter "--help -h")" -- "$cur")'
   echo $'      ;;'
   echo $''
@@ -1367,16 +1389,20 @@ send_completions() {
   echo $'      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_cliferay_completions_filter "--help -h new-api new-instance new-object")" -- "$cur")'
   echo $'      ;;'
   echo $''
-  echo $'    \'sync\'*)'
+  echo $'    \'nuke\'*)'
   echo $'      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_cliferay_completions_filter "--help -h")" -- "$cur")'
   echo $'      ;;'
   echo $''
-  echo $'    \'nuke\'*)'
+  echo $'    \'sync\'*)'
   echo $'      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_cliferay_completions_filter "--help -h")" -- "$cur")'
   echo $'      ;;'
   echo $''
   echo $'    \'gogo\'*)'
   echo $'      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_cliferay_completions_filter "--help -h diag jaxrs:check scr:list unsatisfied")" -- "$cur")'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'kill\'*)'
+  echo $'      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_cliferay_completions_filter "--help -h")" -- "$cur")'
   echo $'      ;;'
   echo $''
   echo $'    \'ant\'*)'
@@ -1416,7 +1442,7 @@ send_completions() {
   echo $'      ;;'
   echo $''
   echo $'    *)'
-  echo $'      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_cliferay_completions_filter "--help --version -h -v ant b backport brian build changed-modules cm curl d db-name deploy elastic-search folder format-source gogo gw ij jira kill morning nuke poshi run sd set-ticket sf stats super-deploy sync tickets tomcat-folder update")" -- "$cur")'
+  echo $'      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_cliferay_completions_filter "--help --version -h -v ant b backport baseline brian build changed-modules cm curl d db-name deploy elastic-search folder format-source gogo gw ij jira kill morning nuke poshi run sd set-ticket sf stats super-deploy sync tickets tomcat-folder update")" -- "$cur")'
   echo $'      ;;'
   echo $''
   echo $'  esac'
@@ -1600,6 +1626,16 @@ cliferay_deploy_command() {
       cp "$(cliferay folder)/../bundles/osgi/test/$JAR" "$(cliferay folder)/../bundles/osgi/modules/"
   elif ! [[ "$PWD" = */*-test ]]; then
       cliferay gw -a depl
+  fi
+}
+
+# :command.function
+cliferay_baseline_command() {
+  # src/commands/baseline.sh
+  if [[ "$PWD" = */portal-kernel || "$PWD" = */portal-impl ]]; then
+      cliferay ant -Dbaseline.jar.report.level=persist clean jar
+  elif ! [[ "$PWD" = */*-test ]]; then
+      cliferay gw baseline
   fi
 }
 
@@ -2062,6 +2098,13 @@ parse_requirements() {
       action="deploy"
       shift
       cliferay_deploy_parse_requirements "$@"
+      shift $#
+      ;;
+
+    baseline)
+      action="baseline"
+      shift
+      cliferay_baseline_parse_requirements "$@"
       shift $#
       ;;
 
@@ -3206,6 +3249,50 @@ cliferay_deploy_parse_requirements() {
 }
 
 # :command.parse_requirements
+cliferay_baseline_parse_requirements() {
+  # :command.fixed_flags_filter
+  while [[ $# -gt 0 ]]; do
+    case "${1:-}" in
+      --help | -h)
+        long_usage=yes
+        cliferay_baseline_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  # :command.command_filter
+  action="baseline"
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_simple
+        printf "invalid argument: %s\n" "$key" >&2
+        exit 1
+
+        ;;
+
+    esac
+  done
+
+}
+
+# :command.parse_requirements
 cliferay_poshi_parse_requirements() {
   # :command.fixed_flags_filter
   while [[ $# -gt 0 ]]; do
@@ -4191,6 +4278,7 @@ run() {
     "super-deploy") cliferay_super_deploy_command ;;
     "format-source") cliferay_format_source_command ;;
     "deploy") cliferay_deploy_command ;;
+    "baseline") cliferay_baseline_command ;;
     "poshi") cliferay_poshi_command ;;
     "run") cliferay_run_command ;;
     "gogo") cliferay_gogo_command ;;
