Adding new-object curl

diff --git a/cliferay b/cliferay
--- a/cliferay
+++ b/cliferay
@@ -674,6 +674,7 @@ cliferay_curl_usage() {
   printf "%s\n" "Commands:"
   printf "  %s   Create a new instance\n" "new-instance"
   printf "  %s   Create a new API Builder API\n" "new-api     "
+  printf "  %s   Create a new object definition with some entries\n" "new-object  "
   echo
 
   # :command.long_usage
@@ -745,6 +746,35 @@ cliferay_curl_new_api_usage() {
   printf "%s\n" "Usage:"
   printf "  cliferay curl new-api\n"
   printf "  cliferay curl new-api --help | -h\n"
+  echo
+
+  # :command.long_usage
+  if [[ -n $long_usage ]]; then
+    printf "%s\n" "Options:"
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "--help, -h"
+    printf "    Show this help\n"
+    echo
+
+  fi
+}
+
+# :command.usage
+cliferay_curl_new_object_usage() {
+  if [[ -n $long_usage ]]; then
+    printf "cliferay curl new-object - Create a new object definition with some entries\n"
+    echo
+
+  else
+    printf "cliferay curl new-object - Create a new object definition with some entries\n"
+    echo
+
+  fi
+
+  printf "%s\n" "Usage:"
+  printf "  cliferay curl new-object\n"
+  printf "  cliferay curl new-object --help | -h\n"
   echo
 
   # :command.long_usage
@@ -871,6 +901,10 @@ send_completions() {
   echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_cliferay_completions_filter "--help -h")" -- "$cur" )'
   echo $'      ;;'
   echo $''
+  echo $'    \'curl new-object\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_cliferay_completions_filter "--help -h")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
   echo $'    \'changed-modules\'*)'
   echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_cliferay_completions_filter "--help -h")" -- "$cur" )'
   echo $'      ;;'
@@ -883,11 +917,11 @@ send_completions() {
   echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_cliferay_completions_filter "--help -h")" -- "$cur" )'
   echo $'      ;;'
   echo $''
-  echo $'    \'curl new-api\'*)'
+  echo $'    \'super-deploy\'*)'
   echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_cliferay_completions_filter "--help -h")" -- "$cur" )'
   echo $'      ;;'
   echo $''
-  echo $'    \'super-deploy\'*)'
+  echo $'    \'curl new-api\'*)'
   echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_cliferay_completions_filter "--help -h")" -- "$cur" )'
   echo $'      ;;'
   echo $''
@@ -920,7 +954,7 @@ send_completions() {
   echo $'      ;;'
   echo $''
   echo $'    \'curl\'*)'
-  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_cliferay_completions_filter "--help -h new-api new-instance")" -- "$cur" )'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_cliferay_completions_filter "--help -h new-api new-instance new-object")" -- "$cur" )'
   echo $'      ;;'
   echo $''
   echo $'    \'sync\'*)'
@@ -1151,53 +1185,7 @@ cliferay_curl_new_instance_command() {
 # :command.function
 cliferay_curl_new_api_command() {
   # src/commands/curl/new-api.sh
-  curl --no-progress-meter -X "POST" "http://localhost:8080/o/object-admin/v1.0/object-definitions" \
-       -H 'Content-Type: application/json' \
-       -u 'test@liferay.com:test' \
-       -d $'{
-    "active": true,
-    "status": {
-      "code": 0
-    },
-    "objectFields": [
-      {
-        "DBType": "String",
-        "indexed": true,
-        "indexedLanguageId": "",
-        "externalReferenceCode": "university-name",
-        "listTypeDefinitionId": 0,
-        "label": {
-          "en_US": "University name"
-        },
-        "type": "String",
-        "required": true,
-        "name": "universityName",
-        "indexedAsKeyword": false
-      }
-    ],
-    "pluralLabel": {
-      "en-US": "Universities"
-    },
-    "portlet": true,
-    "scope": "company",
-    "label": {
-      "en-US": "University"
-    },
-    "externalReferenceCode": "University",
-    "name": "University"
-  }' | jq
-
-  curl --no-progress-meter -X "POST" "http://localhost:8080/o/c/universities/batch" \
-       -H 'Content-Type: application/json' \
-       -u 'test@liferay.com:test' \
-       -d $'[
-    {
-      "universityName": "Oxford"
-    },
-    {
-      "universityName": "Cambridge"
-    }
-  ]' | jq
+  cliferay curl new-object
 
   curl --no-progress-meter -X "POST" "http://localhost:8080/o/headless-builder/applications/" \
        -H 'Content-Type: application/json' \
@@ -1247,6 +1235,68 @@ cliferay_curl_new_api_command() {
 
   curl --no-progress-meter "http://localhost:8080/o/c/my-application/my-endpoint" \
        -u 'test@liferay.com:test' | jq
+}
+
+# :command.function
+cliferay_curl_new_object_command() {
+  # src/commands/curl/new-object.sh
+  JSON=$(
+    curl --no-progress-meter -X "PUT" "http://localhost:8080/o/object-admin/v1.0/object-definitions/by-external-reference-code/University" \
+       -H 'Content-Type: application/json' \
+       -u 'test@liferay.com:test' \
+       -d $'{
+          "active": true,
+          "status": {
+            "code": 0
+          },
+          "objectFields": [
+            {
+              "DBType": "String",
+              "indexed": true,
+              "indexedLanguageId": "",
+              "externalReferenceCode": "university-name",
+              "listTypeDefinitionId": 0,
+              "label": {
+                "en_US": "University name"
+              },
+              "type": "String",
+              "required": true,
+              "system": false,
+              "name": "universityName",
+              "indexedAsKeyword": false
+            }
+          ],
+          "pluralLabel": {
+            "en-US": "Universities"
+          },
+          "portlet": true,
+          "scope": "company",
+          "label": {
+            "en-US": "University"
+          },
+          "externalReferenceCode": "University",
+          "name": "University"
+        }'
+  )
+
+  echo $JSON | jq
+
+  if [[ $(echo $JSON | jq '.status.code') != 0 ]]; then
+    curl --no-progress-meter -X "POST" "http://localhost:8080/o/object-admin/v1.0/object-definitions/$(echo $JSON | jq '.id')/publish" \
+       -u 'test@liferay.com:test' | jq
+  fi
+
+  curl --no-progress-meter -X "POST" "http://localhost:8080/o/c/universities/batch" \
+       -H 'Content-Type: application/json' \
+       -u 'test@liferay.com:test' \
+       -d $'[
+    {
+      "universityName": "Oxford"
+    },
+    {
+      "universityName": "Cambridge"
+    }
+  ]' | jq
 }
 
 # :command.parse_requirements
@@ -2338,6 +2388,13 @@ cliferay_curl_parse_requirements() {
       shift $#
       ;;
 
+    new-object)
+      action="new-object"
+      shift
+      cliferay_curl_new_object_parse_requirements "$@"
+      shift $#
+      ;;
+
     # :command.command_fallback
     "")
       cliferay_curl_usage >&2
@@ -2474,6 +2531,50 @@ cliferay_curl_new_api_parse_requirements() {
 
 }
 
+# :command.parse_requirements
+cliferay_curl_new_object_parse_requirements() {
+  # :command.fixed_flags_filter
+  while [[ $# -gt 0 ]]; do
+    case "${1:-}" in
+      --help | -h)
+        long_usage=yes
+        cliferay_curl_new_object_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  # :command.command_filter
+  action="curl new-object"
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_simple
+        printf "invalid argument: %s\n" "$key" >&2
+        exit 1
+
+        ;;
+
+    esac
+  done
+
+}
+
 # :command.user_hooks
 before_hook() {
   # src/before.sh
@@ -2522,6 +2623,7 @@ run() {
     "curl") cliferay_curl_command ;;
     "curl new-instance") cliferay_curl_new_instance_command ;;
     "curl new-api") cliferay_curl_new_api_command ;;
+    "curl new-object") cliferay_curl_new_object_command ;;
   esac
 }
 
