Adding dependency

diff --git a/cliferay b/cliferay
--- a/cliferay
+++ b/cliferay
@@ -3624,6 +3624,15 @@ cliferay_elastic_search_parse_requirements() {
     esac
   done
 
+  # :command.dependencies_filter
+  if command -v jq >/dev/null 2>&1; then
+    deps['jq']="$(command -v jq | head -n1)"
+  else
+    printf "missing dependency: jq\n" >&2
+    printf "%s\n" "install it from https://jqlang.github.io/jq" >&2
+    exit 1
+  fi
+
   # :command.command_filter
   action="elastic-search"
 
