Adding sf command

diff --git a/cliferay b/cliferay
--- a/cliferay
+++ b/cliferay
@@ -44,6 +44,7 @@ cliferay_usage() {
   printf "%s\n" "Module Commands:"
   printf "  %s   List changed modules\n" "changed-modules"
   printf "  %s   Deploy changed modules\n" "super-deploy   "
+  printf "  %s   Run SF globally\n" "format-source  "
   echo
   printf "%s\n" "Server Commands:"
   printf "  %s   Start the server\n" "run            "
@@ -244,6 +245,38 @@ cliferay_super_deploy_usage() {
   printf "%s\n" "Usage:"
   printf "  cliferay super-deploy\n"
   printf "  cliferay super-deploy --help | -h\n"
+  echo
+
+  # :command.long_usage
+  if [[ -n $long_usage ]]; then
+    printf "%s\n" "Options:"
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "--help, -h"
+    printf "    Show this help\n"
+    echo
+
+  fi
+}
+
+# :command.usage
+cliferay_format_source_usage() {
+  if [[ -n $long_usage ]]; then
+    printf "cliferay format-source - Run SF globally\n"
+    echo
+
+  else
+    printf "cliferay format-source - Run SF globally\n"
+    echo
+
+  fi
+
+  printf "Alias: sf\n"
+  echo
+
+  printf "%s\n" "Usage:"
+  printf "  cliferay format-source\n"
+  printf "  cliferay format-source --help | -h\n"
   echo
 
   # :command.long_usage
@@ -515,6 +548,10 @@ send_completions() {
   echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_cliferay_completions_filter "--help -h")" -- "$cur" )'
   echo $'      ;;'
   echo $''
+  echo $'    \'format-source\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_cliferay_completions_filter "--help -h")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
   echo $'    \'super-deploy\'*)'
   echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_cliferay_completions_filter "--help -h")" -- "$cur" )'
   echo $'      ;;'
@@ -547,7 +584,7 @@ send_completions() {
   echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_cliferay_completions_filter "--help -h")" -- "$cur" )'
   echo $'      ;;'
   echo $''
-  echo $'    \'cm\'*)'
+  echo $'    \'sd\'*)'
   echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_cliferay_completions_filter "--help -h")" -- "$cur" )'
   echo $'      ;;'
   echo $''
@@ -559,12 +596,16 @@ send_completions() {
   echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_cliferay_completions_filter "--help -h")" -- "$cur" )'
   echo $'      ;;'
   echo $''
-  echo $'    \'sd\'*)'
+  echo $'    \'cm\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_cliferay_completions_filter "--help -h")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'sf\'*)'
   echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_cliferay_completions_filter "--help -h")" -- "$cur" )'
   echo $'      ;;'
   echo $''
   echo $'    *)'
-  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_cliferay_completions_filter "--help --version -h -v build changed-modules cm completions folder gw ij kill morning run sd super-deploy sync")" -- "$cur" )'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_cliferay_completions_filter "--help --version -h -v build changed-modules cm completions folder format-source gw ij kill morning run sd sf super-deploy sync")" -- "$cur" )'
   echo $'      ;;'
   echo $''
   echo $'  esac'
@@ -619,6 +660,13 @@ cliferay_super_deploy_command() {
   # src/commands/super-deploy.sh
   cd $(cliferay folder)
   cliferay changed-modules | grep -v test | run-stdin cliferay gw -a deploy
+}
+
+# :command.function
+cliferay_format_source_command() {
+  # src/commands/format-source.sh
+  cd $(cliferay folder)/portal-impl
+  ant format-source-current-branch
 }
 
 # :command.function
@@ -738,6 +786,13 @@ parse_requirements() {
       action="super-deploy"
       shift
       cliferay_super_deploy_parse_requirements "$@"
+      shift $#
+      ;;
+
+    format-source | sf)
+      action="format-source"
+      shift
+      cliferay_format_source_parse_requirements "$@"
       shift $#
       ;;
 
@@ -1092,6 +1147,50 @@ cliferay_super_deploy_parse_requirements() {
 }
 
 # :command.parse_requirements
+cliferay_format_source_parse_requirements() {
+  # :command.fixed_flags_filter
+  while [[ $# -gt 0 ]]; do
+    case "${1:-}" in
+      --help | -h)
+        long_usage=yes
+        cliferay_format_source_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  # :command.command_filter
+  action="format-source"
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_simple
+        printf "invalid argument: %s\n" "$key" >&2
+        exit 1
+
+        ;;
+
+    esac
+  done
+
+}
+
+# :command.parse_requirements
 cliferay_run_parse_requirements() {
   # :command.fixed_flags_filter
   while [[ $# -gt 0 ]]; do
@@ -1335,6 +1434,7 @@ run() {
     "gw") cliferay_gw_command ;;
     "changed-modules") cliferay_changed_modules_command ;;
     "super-deploy") cliferay_super_deploy_command ;;
+    "format-source") cliferay_format_source_command ;;
     "run") cliferay_run_command ;;
     "kill") cliferay_kill_command ;;
     "morning") cliferay_morning_command ;;
