feat(jira) Search in the current branch name for LP[A-Z]-[0-9]

diff --git a/cliferay b/cliferay
--- a/cliferay
+++ b/cliferay
@@ -1092,7 +1092,7 @@ cliferay_jira_usage() {
   printf "cliferay jira - Open a Jira ticket\n\n"
 
   printf "%s\n" "Usage:"
-  printf "  cliferay jira TICKET\n"
+  printf "  cliferay jira [TICKET]\n"
   printf "  cliferay jira --help | -h\n"
   echo
 
@@ -1953,7 +1953,18 @@ cliferay_backport_command() {
 # :command.function
 cliferay_jira_command() {
   # src/commands/jira.sh
-  open "https://liferay.atlassian.net/browse/${args["ticket"]}"
+  TICKET=${args["ticket"]:-$(git rev-parse --abbrev-ref HEAD | grep -oE 'LP[A-Z]-[0-9]+' || true)}
+
+  # var validation
+  if [[ -z "$TICKET" ]]; then
+    printf "mising regex pattern 'LP[A-Z]-[0-9]' in the current git branch\n" >&2
+    printf "missing argment: TICKET\nusage: cliferay jira TICKET\n" >&2\
+
+    exit 1
+  fi
+
+  echo "opening 🌏 https://liferay.atlassian.net/browse/$TICKET"
+  open "https://liferay.atlassian.net/browse/$TICKET"
 }
 
 # :command.parse_requirements
@@ -4221,13 +4232,6 @@ cliferay_jira_parse_requirements() {
 
     esac
   done
-
-  # :command.required_args_filter
-  if [[ -z ${args['ticket']+x} ]]; then
-    printf "missing required argument: TICKET\nusage: cliferay jira TICKET\n" >&2
-
-    exit 1
-  fi
 
 }
 
