Marking gh as a dependency

diff --git a/liferay b/liferay
--- a/liferay
+++ b/liferay
@@ -866,6 +866,15 @@ liferay_sync_parse_requirements() {
     esac
   done
 
+  # :command.dependencies_filter
+  if command -v gh >/dev/null 2>&1; then
+    deps['gh']="$(command -v gh | head -n1)"
+  else
+    printf "missing dependency: gh\n" >&2
+    printf "%s\n" "install it from https://cli.github.com" >&2
+    exit 1
+  fi
+
   # :command.command_filter
   action="sync"
 
