Enabling completions

diff --git a/liferay b/liferay
--- a/liferay
+++ b/liferay
@@ -34,11 +34,12 @@ liferay_usage() {
   echo
   # :command.usage_commands
   printf "%s\n" "Commands:"
-  printf "  %s   Update codebase\n" "update "
-  printf "  %s   Run ant all\n" "build  "
-  printf "  %s   Run liferay-intellij\n" "ij     "
-  printf "  %s   Start the server\n" "run    "
-  printf "  %s   Update, build, ij and run\n" "morning"
+  printf "  %s   Update codebase\n" "update     "
+  printf "  %s   Run ant all\n" "build      "
+  printf "  %s   Run liferay-intellij\n" "ij         "
+  printf "  %s   Start the server\n" "run        "
+  printf "  %s   Update, build, ij and run\n" "morning    "
+  printf "  %s   Enable completions\n" "completions"
   echo
 
   # :command.long_usage
@@ -201,6 +202,35 @@ liferay_morning_usage() {
   fi
 }
 
+# :command.usage
+liferay_completions_usage() {
+  if [[ -n $long_usage ]]; then
+    printf "liferay completions - Enable completions\n"
+    echo
+
+  else
+    printf "liferay completions - Enable completions\n"
+    echo
+
+  fi
+
+  printf "%s\n" "Usage:"
+  printf "  liferay completions\n"
+  printf "  liferay completions --help | -h\n"
+  echo
+
+  # :command.long_usage
+  if [[ -n $long_usage ]]; then
+    printf "%s\n" "Options:"
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "--help, -h"
+    printf "    Show this help\n"
+    echo
+
+  fi
+}
+
 # :command.normalize_input
 normalize_input() {
   local arg flags
@@ -259,6 +289,73 @@ liferay_folder() {
   echo "/home/alex/Projects/liferay/liferay-portal"
 }
 
+# src/lib/send_completions.sh
+send_completions() {
+  echo $'# liferay completion                                       -*- shell-script -*-'
+  echo $''
+  echo $'# This bash completions script was generated by'
+  echo $'# completely (https://github.com/dannyben/completely)'
+  echo $'# Modifying it manually is not recommended'
+  echo $''
+  echo $'_liferay_completions_filter() {'
+  echo $'  local words="$1"'
+  echo $'  local cur=${COMP_WORDS[COMP_CWORD]}'
+  echo $'  local result=()'
+  echo $''
+  echo $'  if [[ "${cur:0:1}" == "-" ]]; then'
+  echo $'    echo "$words"'
+  echo $'  '
+  echo $'  else'
+  echo $'    for word in $words; do'
+  echo $'      [[ "${word:0:1}" != "-" ]] && result+=("$word")'
+  echo $'    done'
+  echo $''
+  echo $'    echo "${result[*]}"'
+  echo $''
+  echo $'  fi'
+  echo $'}'
+  echo $''
+  echo $'_liferay_completions() {'
+  echo $'  local cur=${COMP_WORDS[COMP_CWORD]}'
+  echo $'  local compwords=("${COMP_WORDS[@]:1:$COMP_CWORD-1}")'
+  echo $'  local compline="${compwords[*]}"'
+  echo $''
+  echo $'  case "$compline" in'
+  echo $'    \'completions\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_liferay_completions_filter "--help -h")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'morning\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_liferay_completions_filter "--help -h")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'update\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_liferay_completions_filter "--help -h")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'build\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_liferay_completions_filter "--help -h")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'run\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_liferay_completions_filter "--help -h")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'ij\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_liferay_completions_filter "--help -h")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    *)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_liferay_completions_filter "--help --version -h -v build completions ij morning run update")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'  esac'
+  echo $'} &&'
+  echo $'complete -F _liferay_completions liferay'
+  echo $''
+  echo $'# ex: filetype=sh'
+}
+
 # :command.command_functions
 # :command.function
 liferay_update_command() {
@@ -302,6 +399,12 @@ liferay_morning_command() {
   liferay ij
   liferay run
 
+}
+
+# :command.function
+liferay_completions_command() {
+  # src/completions_command.sh
+  send_completions
 }
 
 # :command.parse_requirements
@@ -365,6 +468,13 @@ parse_requirements() {
       action="morning"
       shift
       liferay_morning_parse_requirements "$@"
+      shift $#
+      ;;
+
+    completions)
+      action="completions"
+      shift
+      liferay_completions_parse_requirements "$@"
       shift $#
       ;;
 
@@ -624,6 +734,50 @@ liferay_morning_parse_requirements() {
 
 }
 
+# :command.parse_requirements
+liferay_completions_parse_requirements() {
+  # :command.fixed_flags_filter
+  while [[ $# -gt 0 ]]; do
+    case "${1:-}" in
+      --help | -h)
+        long_usage=yes
+        liferay_completions_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  # :command.command_filter
+  action="completions"
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_simple
+        printf "invalid argument: %s\n" "$key" >&2
+        exit 1
+
+        ;;
+
+    esac
+  done
+
+}
+
 # :command.initialize
 initialize() {
   version="1.0.0"
@@ -647,6 +801,7 @@ run() {
     "ij") liferay_ij_command ;;
     "run") liferay_run_command ;;
     "morning") liferay_morning_command ;;
+    "completions") liferay_completions_command ;;
   esac
 }
 
