Adding commands to list and deploy changed modules

diff --git a/liferay b/liferay
--- a/liferay
+++ b/liferay
@@ -34,13 +34,16 @@ liferay_usage() {
   echo
   # :command.usage_commands
   printf "%s\n" "Commands:"
-  printf "  %s   Prints the source folder\n" "folder     "
-  printf "  %s   Update codebase\n" "update     "
-  printf "  %s   Run ant all\n" "build      "
-  printf "  %s   Run liferay-intellij\n" "ij         "
-  printf "  %s   Start the server\n" "run        "
-  printf "  %s   Update, build, ij and run\n" "morning    "
-  printf "  %s   Enable completions\n" "completions"
+  printf "  %s   Print the source folder\n" "folder         "
+  printf "  %s   Update codebase\n" "update         "
+  printf "  %s   Run ant all\n" "build          "
+  printf "  %s   Run liferay-intellij\n" "ij             "
+  printf "  %s   Start the server\n" "run            "
+  printf "  %s   Update, build, ij and run\n" "morning        "
+  printf "  %s   List changed modules\n" "changed-modules"
+  printf "  %s   Print gradlew path\n" "gw             "
+  printf "  %s   Deploy changed modules\n" "super-deploy   "
+  printf "  %s   Enable completions\n" "completions    "
   echo
 
   # :command.long_usage
@@ -61,11 +64,11 @@ liferay_usage() {
 # :command.usage
 liferay_folder_usage() {
   if [[ -n $long_usage ]]; then
-    printf "liferay folder - Prints the source folder\n"
+    printf "liferay folder - Print the source folder\n"
     echo
 
   else
-    printf "liferay folder - Prints the source folder\n"
+    printf "liferay folder - Print the source folder\n"
     echo
 
   fi
@@ -233,6 +236,99 @@ liferay_morning_usage() {
 }
 
 # :command.usage
+liferay_changed_modules_usage() {
+  if [[ -n $long_usage ]]; then
+    printf "liferay changed-modules - List changed modules\n"
+    echo
+
+  else
+    printf "liferay changed-modules - List changed modules\n"
+    echo
+
+  fi
+
+  printf "Alias: cm\n"
+  echo
+
+  printf "%s\n" "Usage:"
+  printf "  liferay changed-modules\n"
+  printf "  liferay changed-modules --help | -h\n"
+  echo
+
+  # :command.long_usage
+  if [[ -n $long_usage ]]; then
+    printf "%s\n" "Options:"
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "--help, -h"
+    printf "    Show this help\n"
+    echo
+
+  fi
+}
+
+# :command.usage
+liferay_gw_usage() {
+  if [[ -n $long_usage ]]; then
+    printf "liferay gw - Print gradlew path\n"
+    echo
+
+  else
+    printf "liferay gw - Print gradlew path\n"
+    echo
+
+  fi
+
+  printf "%s\n" "Usage:"
+  printf "  liferay gw\n"
+  printf "  liferay gw --help | -h\n"
+  echo
+
+  # :command.long_usage
+  if [[ -n $long_usage ]]; then
+    printf "%s\n" "Options:"
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "--help, -h"
+    printf "    Show this help\n"
+    echo
+
+  fi
+}
+
+# :command.usage
+liferay_super_deploy_usage() {
+  if [[ -n $long_usage ]]; then
+    printf "liferay super-deploy - Deploy changed modules\n"
+    echo
+
+  else
+    printf "liferay super-deploy - Deploy changed modules\n"
+    echo
+
+  fi
+
+  printf "Alias: sd\n"
+  echo
+
+  printf "%s\n" "Usage:"
+  printf "  liferay super-deploy\n"
+  printf "  liferay super-deploy --help | -h\n"
+  echo
+
+  # :command.long_usage
+  if [[ -n $long_usage ]]; then
+    printf "%s\n" "Options:"
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "--help, -h"
+    printf "    Show this help\n"
+    echo
+
+  fi
+}
+
+# :command.usage
 liferay_completions_usage() {
   if [[ -n $long_usage ]]; then
     printf "liferay completions - Enable completions\n"
@@ -314,6 +410,29 @@ inspect_args() {
 }
 
 # :command.user_lib
+# src/lib/functions.sh
+function get-module() {
+	while read line
+	do
+		if test -f $line/bnd.bnd; then
+			echo "$line";
+		elif [ "$line" != "." ]; then
+			(dirname $line | get-module)
+		fi
+	done
+}
+
+function run-stdin() {
+	while read line
+	do
+		echo "" | (cd $(liferay folder)/$line; $*)
+	done
+}
+
+function liferay-get-modules() {
+	(cd $(liferay folder) && $* --name-only | get-module | uniq)
+}
+
 # src/lib/send_completions.sh
 send_completions() {
   echo $'# liferay completion                                       -*- shell-script -*-'
@@ -346,6 +465,14 @@ send_completions() {
   echo $'  local compline="${compwords[*]}"'
   echo $''
   echo $'  case "$compline" in'
+  echo $'    \'changed-modules\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_liferay_completions_filter "--help -h")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'super-deploy\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_liferay_completions_filter "--help -h")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
   echo $'    \'completions\'*)'
   echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_liferay_completions_filter "--help -h")" -- "$cur" )'
   echo $'      ;;'
@@ -374,8 +501,20 @@ send_completions() {
   echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_liferay_completions_filter "--help -h")" -- "$cur" )'
   echo $'      ;;'
   echo $''
+  echo $'    \'cm\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_liferay_completions_filter "--help -h")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'sd\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_liferay_completions_filter "--help -h")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'gw\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_liferay_completions_filter "--help -h")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
   echo $'    *)'
-  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_liferay_completions_filter "--help --version -h -v build completions folder ij morning run update")" -- "$cur" )'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_liferay_completions_filter "--help --version -h -v build changed-modules cm completions folder gw ij morning run sd super-deploy update")" -- "$cur" )'
   echo $'      ;;'
   echo $''
   echo $'  esac'
@@ -434,6 +573,26 @@ liferay_morning_command() {
   liferay ij
   liferay run
 
+}
+
+# :command.function
+liferay_changed_modules_command() {
+  # src/commands/changed-modules.sh
+  cd $(liferay folder)
+  liferay-get-modules git diff --name-only ${BRANCH:-master}
+}
+
+# :command.function
+liferay_gw_command() {
+  # src/commands/gw.sh
+  echo "$(liferay folder)/gradlew"
+}
+
+# :command.function
+liferay_super_deploy_command() {
+  # src/commands/super-deploy.sh
+  cd $(liferay folder)
+  liferay changed-modules | grep -v test | run-stdin $(liferay gw) -a deploy
 }
 
 # :command.function
@@ -510,6 +669,27 @@ parse_requirements() {
       action="morning"
       shift
       liferay_morning_parse_requirements "$@"
+      shift $#
+      ;;
+
+    changed-modules | cm)
+      action="changed-modules"
+      shift
+      liferay_changed_modules_parse_requirements "$@"
+      shift $#
+      ;;
+
+    gw)
+      action="gw"
+      shift
+      liferay_gw_parse_requirements "$@"
+      shift $#
+      ;;
+
+    super-deploy | sd)
+      action="super-deploy"
+      shift
+      liferay_super_deploy_parse_requirements "$@"
       shift $#
       ;;
 
@@ -821,6 +1001,138 @@ liferay_morning_parse_requirements() {
 }
 
 # :command.parse_requirements
+liferay_changed_modules_parse_requirements() {
+  # :command.fixed_flags_filter
+  while [[ $# -gt 0 ]]; do
+    case "${1:-}" in
+      --help | -h)
+        long_usage=yes
+        liferay_changed_modules_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  # :command.command_filter
+  action="changed-modules"
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_simple
+        printf "invalid argument: %s\n" "$key" >&2
+        exit 1
+
+        ;;
+
+    esac
+  done
+
+}
+
+# :command.parse_requirements
+liferay_gw_parse_requirements() {
+  # :command.fixed_flags_filter
+  while [[ $# -gt 0 ]]; do
+    case "${1:-}" in
+      --help | -h)
+        long_usage=yes
+        liferay_gw_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  # :command.command_filter
+  action="gw"
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_simple
+        printf "invalid argument: %s\n" "$key" >&2
+        exit 1
+
+        ;;
+
+    esac
+  done
+
+}
+
+# :command.parse_requirements
+liferay_super_deploy_parse_requirements() {
+  # :command.fixed_flags_filter
+  while [[ $# -gt 0 ]]; do
+    case "${1:-}" in
+      --help | -h)
+        long_usage=yes
+        liferay_super_deploy_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  # :command.command_filter
+  action="super-deploy"
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_simple
+        printf "invalid argument: %s\n" "$key" >&2
+        exit 1
+
+        ;;
+
+    esac
+  done
+
+}
+
+# :command.parse_requirements
 liferay_completions_parse_requirements() {
   # :command.fixed_flags_filter
   while [[ $# -gt 0 ]]; do
@@ -888,6 +1200,9 @@ run() {
     "ij") liferay_ij_command ;;
     "run") liferay_run_command ;;
     "morning") liferay_morning_command ;;
+    "changed-modules") liferay_changed_modules_command ;;
+    "gw") liferay_gw_command ;;
+    "super-deploy") liferay_super_deploy_command ;;
     "completions") liferay_completions_command ;;
   esac
 }
